# Generated by Django 3.1 on 2020-12-03 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201126_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='boardId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.board'),
        ),
    ]
